@echo off

echo:
echo Installing applications via WinGet...
echo:

winget install --id Microsoft.Office -e -h --accept-source-agreements --accept-package-agreements & winget install --id=Google.Chrome -e -h --accept-source-agreements --accept-package-agreements & winget install --id=Mozilla.Firefox -e -h --accept-source-agreements --accept-package-agreements & winget install --id=Adobe.Acrobat.Reader.64-bit -e -h --accept-source-agreements --accept-package-agreements & winget install --id=Zoom.Zoom -e -h --accept-source-agreements --accept-package-agreements & winget install --id=Microsoft.Skype -e -h --accept-source-agreements --accept-package-agreements & winget install --id=7zip.7zip -e -h --accept-source-agreements --accept-package-agreements & winget install --id=VideoLAN.VLC -e -h --accept-source-agreements --accept-package-agreements & winget install --id=AdoptOpenJDK.OpenJDK.14 -e -h --accept-source-agreements --accept-package-agreements & winget install --id=AdoptOpenJDK.OpenJDK.15 -e -h --accept-source-agreements --accept-package-agreements & winget install --id=AdoptOpenJDK.OpenJDK.16 -e -h --accept-source-agreements --accept-package-agreements & winget install --id=AdoptOpenJDK.OpenJDK.17 -e -h --accept-source-agreements --accept-package-agreements & winget install --id=AdoptOpenJDK.OpenJDK.11 -e -h --accept-source-agreements --accept-package-agreements & winget install --id=AdoptOpenJDK.OpenJDK.8 -e -h --accept-source-agreements --accept-package-agreements & winget install --id=Microsoft.DotNet.Runtime.3_1 -e -h --accept-source-agreements --accept-package-agreements & winget install --id=Microsoft.DotNet.Runtime.5 -e -h --accept-source-agreements --accept-package-agreements & winget install --id=Microsoft.DotNet.Runtime.6 -e -h --accept-source-agreements --accept-package-agreements & winget install --id=Microsoft.dotnetRuntime.3-x64 -e -h --accept-source-agreements --accept-package-agreements & winget install --id=Microsoft.DotNet.AspNetCore.3_1 -e -h --accept-source-agreements --accept-package-agreements & winget install --id=Microsoft.DotNet.AspNetCore.5 -e -h --accept-source-agreements --accept-package-agreements & winget install --id=Microsoft.DotNet.AspNetCore.6 -e -h --accept-source-agreements --accept-package-agreements & winget install --id=Microsoft.DotNet.DesktopRuntime.6 -e -h --accept-source-agreements --accept-package-agreements & winget install --id=Microsoft.DotNet.DesktopRuntime.5 -e -h --accept-source-agreements --accept-package-agreements & winget install --id=Microsoft.DotNet.DesktopRuntime.3_1 -e -h --accept-source-agreements --accept-package-agreements

echo:
echo All applications should now be installed.

timeout 3